dotfiles_root="${HOME}/.dotfiles"

if [ -r "${dotfiles_root}/zsh/init.zsh" ]; then
  source "${dotfiles_root}/zsh/init.zsh"
fi

if [ -r "${dotfiles_root}/zsh/ghq-clone.zsh" ]; then
  source "${dotfiles_root}/zsh/ghq-clone.zsh"
fi
